### ISSUE TITLE
[WARNING] REST API: job without any resources/hosts

### ISSUE THREAD

**Issue by Autumn-Roy** [pc2/cc-slurm-sync#1]
When I use cc-slurm-sync to start_job in cc-backend, the server notice that [WARNING] REST API: job without any resources/hosts.
I checked my config.json ,like this:
`{
        "slurm" : {
                "squeue": "/usr/bin/squeue",
                "sacct": "/usr/bin/sacct",
                "state_save_location" : "/var/spool/SLURM/StateSaveLocation"
        },
        "cc-backend" : {
                "host" : "http://<my_host>:39000",
                "apikey" : "eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2Njc4OTg1NDIsInJvbGVzIjpbImFwaSJdLCJzdWIiOiJzbHVybSJ9.tvSyPYBFRslez_hl9nT6nrKBSAQ9YYnPqagBuIg1AWkJi5YSoFWS2LbxuCVWAjwxOQDrTXIMHUlF4MSMpl2_CQ"
        },
        "accelerators" : {
        },
        "node_regex" : "^(n2(lcn|cn|fpga|gpu)[\\d{2,4}\\,\\-\\[\\]]+)+$"
}
`
Is there any things wrong?

**Comment by oscarminus** [comment]
What I notice is that the regex for the node names has not been adjusted. I assume, that your node names are different to that string. This is used to validate the node names before passing them to a slurm command to generate a node list. Keep in mind, that every \ has to be escaped.

**Comment by Autumn-Roy** [comment]
Thank you for answering, it's very helpful for me.
